version: '3.5'

services:
  db:
    image: parabible-postgresql
    container_name: parabible-db
    restart: unless-stopped
    build: 
      context: ./postgres
    env_file:
      - ./postgres/db.env
    command: -p 5432
    ports:
      - ${DB_PORT}:5432
    networks:
      - db_backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 600s
      timeout: 5s
      retries: 5

  front:
    image: parabible-flask
    container_name: parabible-front
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    build:
      context: ./web
    env_file:
      - ./web/conf.env
    ports:
      - ${PY_PORT}:5000
    networks:
      - db_backend

networks:
  db_backend:
    name: db_backend
